# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.ImageField(upload_to=b'documents/%Y/%m/%d'),
        ),
    ]
