# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160323_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.ImageField(upload_to=b'documents/')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
