# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20160323_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_link', models.ImageField(upload_to=b'documents/')),
                ('image_caption', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='packageimages',
            name='image_text',
            field=models.CharField(default=b'', max_length=10),
        ),
    ]
