# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20160324_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_name', models.CharField(max_length=30)),
                ('package_image', models.ImageField(upload_to=b'package_detail_image/')),
                ('package_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.PackageImages')),
                ('package_small_desc', models.CharField(max_length=250)),
                ('package_modal_body', models.CharField(max_length=1000)),
                ('package_itenary', models.FileField(upload_to=b'itenaries/')),
            ],
        ),
        migrations.AlterField(
            model_name='packageimages',
            name='image_link',
            field=models.ImageField(upload_to=b'package_image/'),
        ),
        migrations.AlterField(
            model_name='sliderimages',
            name='slider_link',
            field=models.ImageField(upload_to=b'slider_images/'),
        ),
    ]
