# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20160324_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_modal_body',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_small_desc',
            field=models.CharField(max_length=1000),
        ),
    ]
