# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20160324_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.FileField(upload_to=b'videos/')),
            ],
        ),
    ]
