# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_testimonialvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('tour', models.CharField(max_length=50)),
            ],
        ),
    ]
